version: '3'

vars:
  IMAGE_NAME: credit-load-img
  VERSION: 1.0
  REGION: eu-central-1
  PLATFORM: docker
  AWS_APP: credit-loan-application
  ENV_NAME: credit-loan-new-env

tasks:
  build_docker_image:
    cmds:
      - echo "Building Docker Image"
      - docker build -t {{.IMAGE_NAME}}:{{.VERSION}} -f Dockerfile .

  eb_init:
    cmds:
      - echo "Initializing Elastic Beanstalk App"
      - eb init -p {{.PLATFORM}} -r {{.REGION}} {{.AWS_APP}}

  eb_env:
    cmds:
      - echo "Creating or ensuring environment exists"
      - eb create {{.ENV_NAME}} -r {{.REGION}} --single  

  deploy:
    cmds:
      - echo "Deploying Docker image to AWS Elastic Beanstalk"
      - eb deploy

  full_deploy:
    cmds:
      - echo "Full deployment process"
      - build_docker_image
      - eb_init
      - eb_env  
      - deploy

